### ISSUE TITLE
Publish 1.1.0 version

### ISSUE THREAD

**Issue by mesilov** [bitrix24/b24phpsdk#34]
### Description

Publish 1.1.0 sdk version

**Added**
- [x] Add documentation and example «if in sdk method not implemented» #15
- [x] Make core public in service builder #26
- [x] Add super-simple kick-off guide #17
- [x] Add documentation and examples for store tokens in the local application #29
- [x] #42

**Bugfix**
- [x] Wrong variable name #30 
- [x] Wrong API-client and sdk version in headers #13

## Publishing process
- [x] finish PR
- [x] Write release notes documentation 
- [x] update version README.md
- [x] update version in examples/
